
  - name: Start list of options
    lineinfile: dest={{ ansibleResultFile }} line="[" create="yes"

  - name: Write options data out to ansible result file
    lineinfile: dest={{ ansibleResultFile }} line=" {\"name\":\"{{ item.name }}\",\"id\":\"{{ item.id }}\"}," 
    with_items: "{{optionsData|default([])}}"

  - name: Remove last comma
    lineinfile: dest={{ ansibleResultFile }} regexp="^(.*),$" line="\1" backrefs=yes

  - name: Write out end of options list
    lineinfile: dest={{ ansibleResultFile }} line="]" 
