
  - name: Start list of options
    lineinfile: dest={{ ansibleResultFile }} line="[" create="yes"

  - name: Write options data out to ansible result file
    lineinfile: dest={{ ansibleResultFile }} line=" {\"name\":\"{{ item.name }}\",\"id\":\"{{ item.id }}\"}," 
    with_items: "{{optionsData}}"

  - name: Remove last comma
    lineinfile: dest={{ ansibleResultFile }} regexp="^(.*),$" line="\1" backrefs=yes

  - name: Add None option to list of options
    lineinfile: dest={{ ansibleResultFile }} line=" ,{\"name\":\"None\",\"id\":\"null\"}"
    when: (includeOptionNone is defined) and includeOptionNone

  - name: Write out end of options list
    lineinfile: dest={{ ansibleResultFile }} line="]" 
