---
- hosts: localhost 
  gather_facts: False
  tasks:

  - fail: msg="Failed to get options for Export for Volume.  No project defined"
    when: ProjectForExport is undefined

  - name: Logging in to ViPR
    include: playbook-vipr-login.yml

  - name: Get Volume IDs
    include: playbook-vipr-options-VolumesForExport-getVols.yml

  - name: Get exported volume IDs
    include: playbook-vipr-options-VolumesForExport-getExpdVols.yml
    when: vol_ids is defined

  - name: Get unexported volumes by removing exported vols from list of all vols
    set_fact: unexp_vol_ids_items={{item}}
    with_items: vol_ids
    when: item not in exp_vol_ids
    register: unexp_vol_ids_result

  - name: Make list of unexported volume lists
    set_fact: unexp_vol_ids="{{unexp_vol_ids_result.results|selectattr('ansible_facts','defined')|map(attribute='ansible_facts.unexp_vol_ids_items')|list}}"
    when: unexp_vol_ids_result.results is defined

  - name: Use empty list if none are exported
    set_fact: unexp_vol_ids="[]"
    when: unexp_vol_ids is undefined

  - name: Log unexported volume IDs found
    debug: var=unexp_vol_ids

  - name: Get volume info for unexported volume IDs
    set_fact: path="/block/volumes/bulk.json"
    when: unexp_vol_ids is defined

  - name: Make body with volume IDs
    set_fact: body="{"id":{{unexp_vol_ids}}}"
    when: (unexp_vol_ids is defined) and (unexp_vol_ids|length > 0)

  - name: Make empty body if no IDs
    set_fact: body="{\"id\":[]}"
    when: (unexp_vol_ids is defined) and (unexp_vol_ids|length < 1)

  - name: Issue REST request to get volume details
    include: playbook-rest-request.yml
    when: unexp_vol_ids is defined

  - name: Logout from ViPR
    include: playbook-vipr-logout.yml

  - name: Get results from REST request
    set_fact: restResult_json_volume="{{restResult.json.volume}}"
    when: restResult.json.volume is defined

  - name: Make empty response if no results
    set_fact: restResult_json_volume="[]"
    when: restResult.json.volume is undefined

  - name: Get menu option data for volumes, except RP vols that are not 'source' or 'target' type, & internal vols 
    set_fact: {
       vol_options: {
          "name": "{{item.name}}","id": "{{item.id}}"
          }
       }
    with_items: "{{ restResult_json_volume }}"
    when: (item.internal == "false") or (item.protection is undefined) or (item.protection.recoverpoint is undefined) or (item.protection.recoverpoint.personality is undefined) or (item.protection.recoverpoint.personality == "SOURCE") or (item.protection.recoverpoint.personality == "TARGET")
    register: vol_options_results

  - name: Format options from results
    set_fact: optionsData="{{vol_options_results.results|selectattr('ansible_facts','defined')|map(attribute='ansible_facts.vol_options')|list}}"
    when: vol_options_results.results is defined

  - name: Write out options in correct format
    include: playbook-vipr-options-write.yml

