---
- hosts: localhost 
  gather_facts: False
  tasks:

  - name: Getting AssetOptions for BlockStorageTypeForExport
    debug: var=ansibleResultFile

  - lineinfile: dest={{ ansibleResultFile }} line="[" create="yes"

  - lineinfile: 
        dest={{ ansibleResultFile }} 
        line=" {\"name\":\"Shared\",\"id\":\"shared\"},{\"name\":\"Exclusive\",\"id\":\"exclusive\"}"

  - lineinfile: dest={{ ansibleResultFile }} line="]"
