---
- hosts: localhost 
  gather_facts: False
  tasks:

  - name: Getting AssetOptions for Varray
    include: playbook-vipr-login.yml

  - set_fact: path="/vdc/varrays/bulk.json" #API path to get IDs
  - include: playbook-rest-request.yml 

  - set_fact: path="/vdc/varrays/bulk.json" # API path to get objects
  - set_fact: body="{{ restResult.json }}"  #POST IDs from previous request"
  - include: playbook-rest-request.yml

  - include: playbook-vipr-logout.yml

  - set_fact: optionsData="{{restResult.json.varray}}"
  - include: playbook-vipr-options-write.yml 
