---
- hosts: all 
  tasks:

  - file: path={{ansibleResultFile}} state=touch mode="u=rw,g=r,o=r"
  - command: /usr/bin/truncate -s 0 {{ ansibleResultFile }}

  - lineinfile: dest={{ ansibleResultFile }} line="["

  - lineinfile: dest={{ ansibleResultFile }} 
                line="{\"name\":\""{{ item }}"\",\"id\":\""{{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] }}"\"},"
    with_items:
      - "{{ansible_interfaces}}"
    when: hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] is defined

    # replace last instance of line ending with comma with line, minus the comma
  - lineinfile: dest={{ ansibleResultFile }} regexp="^(.*),$" line="\1" backrefs=yes
    # end file with bracket for end of list
  - lineinfile: dest={{ ansibleResultFile }} line="]"

  - fetch: src={{ ansibleResultFile }} dest={{ ansibleResultFile }} flat=yes 
