
  - name: Getting ViPR creds from include file
    include: playbook-vipr-creds.yml

  - name: Login to ViPR
    uri:
      url: https://{{ host_address }}:{{ api_port }}/login
      validate_certs: no
      user: "{{ login_user }}"
      password: "{{ login_password }}"
      return_content: yes
    ignore_errors: yes 
    register: loginResults

  - name: Determining success based on HTTP return code
    set_fact: loginSucceeded={{ loginResults.status|int < 300 }}
  - name: Saving ViPR login token
    set_fact: loginToken={{ loginResults.x_sds_auth_token }}

  - name: Logging REST results if failed
    debug: var=loginResults
    when: not loginSucceeded

  - name: If login fails, write results out to Ansible results file
    lineinfile: dest={{ ansibleResultFile }} line="{{ loginResults.content }}" create="yes" 
    when: not loginSucceeded

  - name: Fail playbook if login fails
    fail: msg="Login failed"
    when: not loginSucceeded 
