
  - name: touch and truncate ansible result file {{ansibleResultFile}}
    file: path={{ansibleResultFile}} state=touch mode="u=rw,g=r,o=r" 
  - command: /usr/bin/truncate -s 0 {{ ansibleResultFile }} 

  - name: Start list of options
    lineinfile: dest={{ ansibleResultFile }} line="["

  - name: Write options data out to ansible result file
    lineinfile: dest={{ ansibleResultFile }} line=" {\"name\":\"{{ item.name }}\",\"id\":\"{{ item.id }}\"}," 
    with_items: "{{optionsData}}"

  - name: Remove last comma
    lineinfile: dest={{ ansibleResultFile }} regexp="^(.*),$" line="\1" backrefs=yes

  - name: Write out end of options list
    lineinfile: dest={{ ansibleResultFile }} line="]" 
