
  - name: Setting port for REST request to 4443
    set_fact: port="4443"

  - name: setting host address to inventory hostname if not set already
    set_fact: host_address="{{ inventory_hostname }}"
    when: host_address is undefined

    # for convenience, default to POST if body defined
  - name: defaulting REST method to POST
    set_fact: method="POST"
    when: (body is defined) and
          (method is undefined)

    # make REST request
  - name: REST Request
    uri:
      url: https://{{ host_address }}:{{ port }}{{ path_included|default(path) }}
      validate_certs: no  # TODO: enable for production
      HEADER_X-SDS-AUTH-TOKEN: "{{ loginToken|default(omit) }}"
      HEADER_Content-Type: "application/json"
      body_format: json
      method: "{{ method|default('GET') }}"
      body: "{{ body|default(omit) }}"
      return_content: yes
    ignore_errors: yes  # so we can get response into result file
    register: restResult

    #TODO: make sure response only includes data this tenant should see
