  - name: Logout of ViPR
    uri:
      url: https://{{ inventory_hostname }}:{{ api_port }}/logout
      validate_certs: no
      HEADER_X-SDS-AUTH-TOKEN: "{{loginResults.x_sds_auth_token}}"
    register: logoutResults   # get results of last call in this var
  - debug: var=logoutResults  # print out var in ansible log
