
   # un-escape the returned XML string
  - set_fact: elementsXml='{{ createResult.content | regex_replace("\"", "\'") }}'  #' 

    # extract IDs from XML response
  - xml: 
      xmlstring: "{{ elementsXml }}" 
      xpath: "/tasks/task/resource/id"
      content: text
    register: element_ids

    # extract Names from XML
  - xml:
      xmlstring: "{{ elementsXml }}"
      xpath: "/tasks/task/resource/name"
      content: text
    register: element_names


    # Log file name to write to (that was passed in)
  - debug: msg="Writing ansible result to {{ ansibleResultFile }}"

    # begin array 
  - lineinfile: dest={{ ansibleResultFile }} line="[" create="yes"

    # write name of volume created 
  - lineinfile: dest={{ ansibleResultFile }} line="{\"key\":\"{{ item.1.name }}\",\"value\":\"{{ item.0.id }}\"}," 
    with_together:
      - "{{element_ids.matches}}"
      - "{{element_names.matches}}"

    # remove last comma 
  - lineinfile: dest={{ ansibleResultFile }} regexp="^(.*),$" line="\1" backrefs=yes

    # end array
  - lineinfile: dest={{ ansibleResultFile }} line="]" 
