  - name: Logout of ViPR
    uri:
      url: https://{{ host_address }}:{{ api_port }}/logout
      validate_certs: no
      HEADER_X-SDS-AUTH-TOKEN: "{{loginToken}}"
    register: logoutResults   # get results of last call in this var 
