--- 
- name:  set up facts
  hosts: rackhd
  become: yes 
  tasks:

  - set_fact: scaleio_password="Cluster1!"
  - debug: var=scaleio_password

  - set_fact: scaleio_mdm_primary_ip="{{ Interface }}" #"
  - debug: var=scaleio_mdm_primary_ip

  - set_fact: scaleio_mdm_primary_hostname="{{ ansible_fqdn }}" #"
  - debug: var=scaleio_mdm_primary_hostname


  - debug: var=inventory_hostname

    #-------------- common ----------------
  - name: install required packages
    yum: name="{{ item }}" state=latest   #"
    with_items:
       - numactl
       - libaio
    #-------------------------------------- 
  - name: install pre-requisite packages
    yum: name={{ item }} state=latest
    with_items:
    - mutt
    - bash-completion
    - python
  
  - name: pre-requisite on rhel6 based os
    sysctl: name=kernel.shmmax value=209715200
    when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "6" 
    #--------------------------------------------------
    #- include: ../../install_scaleio.yml
  - name: copy files
    copy: src="{{ item }}" dest="/var/tmp/" mode="0644"
    register: file
    with_fileglob:
      - "files/*mdm*.rpm"
  
  - name: install package
    yum: name="{{ file.results[0].dest }}" state="present"
    environment:
      MDM_IP: "{{scaleio_mdm_primary_ip}}"
    #--------------------------------------------------
  
  - name: add primary mdm
    command: scli --add_primary_mdm --primary_mdm_ip {{ scaleio_mdm_primary_ip }} --accept_license
    run_once: true
    delegate_to: "{{ inventory_hostname }}"  #scaleio_mdm_primary_hostname }}"
    ignore_errors: true
    register: add_primary_mdm
    changed_when: "'already configured' not in add_primary_mdm.stderr"
  
  - name: wait for mdm to be active
    wait_for: port=6611 state=started
    run_once: true
    delegate_to: "{{ inventory_hostname }}"  #scaleio_mdm_primary_hostname }}"
  
  - name: initial login
    command: scli --login --username admin --password admin
    run_once: true
    delegate_to: "{{ inventory_hostname }}"  #scaleio_mdm_primary_hostname }}"
    ignore_errors: true
    register: initial_login
  
  - name: login with new password
    command: scli --login --username admin --password "{{ scaleio_password }}"
    run_once: true
    delegate_to: "{{ inventory_hostname }}"  #scaleio_mdm_primary_hostname }}"
    when: initial_login.rc == 7
  
  - name: set password
    command: scli --set_password --old_password admin --new_password "{{ scaleio_password }}"
    run_once: true
    delegate_to: "{{ inventory_hostname }}"  #scaleio_mdm_primary_hostname }}"
    when: initial_login.rc == 0
