---
- hosts: rackhd
  tasks:

  - file: path={{ansibleResultFile}} state=touch mode="u=rw,g=r,o=r"
  - command: /usr/bin/truncate -s 0 {{ ansibleResultFile }}

  - lineinfile: dest={{ ansibleResultFile }} line="["

  - lineinfile: dest={{ ansibleResultFile }} 
                line=" {\"name\":\"{{ item }} ({{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] }})\",\"id\":\"{{ hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] }}\"},"
    with_items:
      - "{{ansible_interfaces}}"
    when: hostvars[inventory_hostname]['ansible_' + item]['ipv4']['address'] is defined

  - lineinfile: dest={{ ansibleResultFile }} line=" {\"name\":\"None\",\"id\":\"null\"}"

    # end file with bracket for end of list
  - lineinfile: dest={{ ansibleResultFile }} line="]"

  - fetch: src={{ ansibleResultFile }} dest={{ ansibleResultFile }} flat=yes 
