
  - set_fact: body='{"count":"{{ NumberOfVolumes }}","name":"{{ VolumeName }}","project":"{{ Project }}","size":"{{ Size }}","varray":"{{ VirtualArray }}","vpool":"{{ VirtualPool }}" }' #" 

  - set_fact: path="/block/volumes.json"

  - include: playbook-rest-request.yml

    # ansibleResultFile is passed in by RackHD's ansible-job.js
  - lineinfile: dest='{{ ansibleResultFile }}' line='{{ restResult.content }}' create='yes'

  - fail: msg="Create Volume {{ VolumeName }} failed"
    when: restResult.status|int < 300

